import fs from "fs-extra";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { resolveVddPaths, resolveAgentInstallPath } from "./paths.js";
import {
  renderAgentsMdCompatibility,
  renderAllAgentTemplates,
  renderInstallManifest
} from "./templates.js";
import { loadPacks } from "../runtime/pack-loader.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function resolveVddSourceRoot(projectRoot: string): Promise<string> {
  const candidates = [
    projectRoot,
    path.resolve(__dirname, "../.."),
    path.resolve(__dirname, "../../..")
  ];

  for (const candidate of candidates) {
    if (await fs.pathExists(path.join(candidate, "agents"))) {
      return candidate;
    }
  }

  throw new Error("Unable to locate the canonical VDD source root.");
}

export interface GenericInstallResult {
  ok: boolean;
  agentsInstalled: string[];
  skipped: string[];
  compatibilityFilesInstalled: string[];
  compatibilityFilesSkipped: string[];
  vddDir: string;
  agentsDir: string;
  agentsMdPath: string;
  manifestPath: string;
  errors: string[];
}

export async function installGeneric(
  projectRoot: string
): Promise<GenericInstallResult> {
  const vddSourceRoot = await resolveVddSourceRoot(projectRoot);
  const paths = resolveVddPaths(projectRoot);
  const agentsInstallDir = resolveAgentInstallPath(projectRoot, "generic-agents-md", "project");
  const agentsMdPath = path.join(projectRoot, "AGENTS.md");

  const errors: string[] = [];
  const agentsInstalled: string[] = [];
  const skipped: string[] = [];
  const compatibilityFilesInstalled: string[] = [];
  const compatibilityFilesSkipped: string[] = [];
  const generatedAgentsMdMarker = "Generated by VDD compatibility export";

  // Scaffold .vdd/ structure
  await fs.ensureDir(paths.vddDir);
  await fs.ensureDir(paths.addonsDir);
  await fs.ensureDir(path.join(paths.addonsDir, "installed", "local"));
  await fs.ensureDir(agentsInstallDir);

  // Scaffold project-state.json if missing
  if (!(await fs.pathExists(paths.stateFile))) {
    await fs.writeJson(
      paths.stateFile,
      {
        vdd: true,
        stage: "init",
        status: "active",
        createdAt: new Date().toISOString()
      },
      { spaces: 2 }
    );
  }

  // Render and write all core agents to .vdd/agents/
  const agents = await renderAllAgentTemplates(vddSourceRoot);

  for (const agent of agents) {
    const destFile = path.join(agentsInstallDir, agent.fileName);

    if (await fs.pathExists(destFile)) {
      skipped.push(agent.name);
      continue;
    }

    try {
      await fs.writeFile(destFile, agent.content, "utf8");
      agentsInstalled.push(agent.name);
    } catch (err) {
      errors.push(
        `Failed to write agent ${agent.name}: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }

  try {
    const agentsMd = renderAgentsMdCompatibility({
      version: "0.1.0",
      agents
    });

    if (await fs.pathExists(agentsMdPath)) {
      const existingContent = await fs.readFile(agentsMdPath, "utf8");
      if (existingContent.includes(generatedAgentsMdMarker)) {
        await fs.writeFile(agentsMdPath, agentsMd, "utf8");
        compatibilityFilesInstalled.push("AGENTS.md");
      } else {
        compatibilityFilesSkipped.push("AGENTS.md");
      }
    } else {
      await fs.writeFile(agentsMdPath, agentsMd, "utf8");
      compatibilityFilesInstalled.push("AGENTS.md");
    }
  } catch (err) {
    errors.push(
      `Failed to write compatibility file AGENTS.md: ${err instanceof Error ? err.message : String(err)}`
    );
  }

  let activePacks: string[] = [];
  try {
    const packs = await loadPacks(projectRoot);
    activePacks = packs.map((p) => p.manifest.name);
  } catch {
    // Non-fatal
  }

  const manifest = renderInstallManifest({
    version: "0.1.0",
    target: "generic-agents-md",
    scope: "project",
    agentsInstalled,
    packs: activePacks
  });

  await fs.writeFile(paths.manifestFile, manifest, "utf8");

  return {
    ok: errors.length === 0,
    agentsInstalled,
    skipped,
    compatibilityFilesInstalled,
    compatibilityFilesSkipped,
    vddDir: paths.vddDir,
    agentsDir: agentsInstallDir,
    agentsMdPath,
    manifestPath: paths.manifestFile,
    errors
  };
}
