import fs from "fs-extra";
import path from "node:path";

// VDD Core agents that get installed into the target runtime
export const CORE_AGENTS = [
  "orchestrator",
  "planner",
  "architect",
  "detailer",
  "researcher",
  "qa-guardian",
  "handoff-manager"
] as const;

export type CoreAgentName = (typeof CORE_AGENTS)[number];

export interface RenderedAgent {
  name: string;
  fileName: string;
  content: string;
}

export interface AgentsMdCompatibilityOptions {
  version: string;
  agents: RenderedAgent[];
}

/**
 * Reads the canonical AGENT.md from the VDD source agents directory
 * and returns it ready to be written to the install target.
 */
export async function renderAgentTemplate(
  vddSourceRoot: string,
  agentName: CoreAgentName
): Promise<RenderedAgent> {
  const agentFile = path.join(vddSourceRoot, "agents", agentName, "AGENT.md");

  if (!(await fs.pathExists(agentFile))) {
    throw new Error(`Agent template not found: ${agentFile}`);
  }

  const content = await fs.readFile(agentFile, "utf8");
  const fileName = `vdd-${agentName}.md`;

  return { name: agentName, fileName, content };
}

/**
 * Renders all core VDD agents from source.
 */
export async function renderAllAgentTemplates(
  vddSourceRoot: string
): Promise<RenderedAgent[]> {
  const results: RenderedAgent[] = [];

  for (const agentName of CORE_AGENTS) {
    const agentFile = path.join(vddSourceRoot, "agents", agentName, "AGENT.md");
    const exists = await fs.pathExists(agentFile);

    if (exists) {
      results.push(await renderAgentTemplate(vddSourceRoot, agentName));
    } else {
      // Silently skip agents not yet written — non-fatal during install
      console.warn(`  [skip] Agent template not found: agents/${agentName}/AGENT.md`);
    }
  }

  return results;
}

/**
 * Generates the content for the VDD install manifest file.
 */
export function renderInstallManifest(options: {
  version: string;
  target: string;
  scope: string;
  agentsInstalled: string[];
  packs: string[];
}): string {
  return JSON.stringify(
    {
      vdd: true,
      version: options.version,
      installedAt: new Date().toISOString(),
      target: options.target,
      scope: options.scope,
      agentsInstalled: options.agentsInstalled,
      activePacks: options.packs
    },
    null,
    2
  );
}

export function renderAgentsMdCompatibility(
  options: AgentsMdCompatibilityOptions
): string {
  const agentLines = options.agents
    .map((agent) => `- \`.vdd/agents/${agent.fileName}\``)
    .join("\n");

  return `# Vibe Driven Dev Compatibility Layer

This project installs VDD as a canonical workflow layer and exposes it through a portable \`AGENTS.md\` contract.

## Role and Operating Mode

You are operating inside a VDD-managed project. Treat the VDD workspace as the source of truth for execution flow, delivery stages, and handoff quality.

## Canonical Agent Exports

The following VDD agent contracts are exported into \`.vdd/agents/\`:

${agentLines}

## Working Rules

1. Start from the VDD project state in \`.vdd/project-state.json\` when it exists.
2. Prefer the canonical VDD agents in \`.vdd/agents/\` over ad hoc workflows.
3. Use \`vdd scan\`, \`vdd status\`, and \`vdd validate <sourceId>\` to inspect project runtime state.
4. Treat installed packs in \`.vdd/packs.json\` as executable extensions only after validation.
5. Keep changes minimal, testable, and aligned to the current project stage.

## Notes

- Generated by VDD compatibility export v${options.version}
- This file is intended for AGENTS.md-aware runtimes such as Cursor, Windsurf, OpenCode, and other compatible tools
`;
}
